metros = (input('Uma distancia em metros: ')).replace(',', '.')
metros = float(metros)
print('A medida de {:.1f}m corresponde a'.format(metros))
print('{}km'.format(metros/1000))
print('{}hm'.format(metros/100))
print('{}dam'.format(metros/10))
print('{:.1f}dm'.format(metros*10))
print('{:.0f}cm'.format(metros*100))
print('{:.0f}mm'.format(metros*1000))
